version: '3.7'

services:
  zoo1:
    image: k9-zookeeper
    restart: always
    hostname: host1
    ports:
      - 2181:2181
      - 8090:8080
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_LOG4J_PROP: INFO,ROLLINGFILE
      U_ID: 1030
    volumes:  
      - type: bind
        source: /home/orange/myzookeeper
        target: /logs

  zoo2:
    image: k9-zookeeper
    restart: always
    hostname: host2
    ports:
      - 2182:2181
      - 8091:8080
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_LOG4J_PROP: INFO,ROLLINGFILE
      U_ID: 1030
    volumes:  
      - type: bind
        source: /home/orange/myzookeeper
        target: /logs

  zoo3:
    image: k9-zookeeper
    restart: always
    hostname: host3
    ports:
      - 2183:2181
      - 8092:8080
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
      ZOO_LOG4J_PROP: INFO,ROLLINGFILE
      U_ID: 1030
    volumes:  
      - type: bind
        source: /home/orange/myzookeeper
        target: /logs
